language: php

branches:
  only:
    - master
    - dev

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpcs --standard=./phpcs.xml -v --encoding=utf-8 ./src
  - vendor/bin/phpunit -c phpunit.xml --debug --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

